#  Copyright (C) 2003-2017, e-Evolution Consultants S.A. , http://www.e-evolution.com
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#  Email: victor.perez@e-evolution.com, http://www.e-evolution.com , http://github.com/e-Evolution
#

version: '3.5'
services:
  db:
    image: postgres:${PG_VERSION}
    ports:
      - "${ADEMPIERE_DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/${PG_VERSION}/data
    networks:
      - custom
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:'${ADEMPIERE_DB_ADMIN_PASSWORD}'
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA:/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS:''
      - POSTGRES_INITDB_XLOGDIR:''

volumes:
 db:
  external: true

networks:
  custom:
    external : true
